
name: al_quran_superapp
description: Complete Al-Quran SuperApp for Malaysia & Indonesia (JAKIM/JAIS Compliant)
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.0.5
  get: ^4.6.6
  
  # Networking
  http: ^0.13.5
  dio: ^5.3.3
  
  # Database (Offline Support)
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Audio Player
  audioplayers: ^5.2.0
  just_audio: ^0.9.35
  
  # Location & Prayer Times
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_qiblah: ^2.1.1
  adhan: ^1.2.0
  
  # Share & Image Generation
  share_plus: ^7.2.1
  screenshot: ^2.1.0
  image: ^4.1.3
  
  # Localization
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  
  # Notifications
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.0
  
  # Video Player (PeaceTV Streaming)
  video_player: ^2.8.1
  chewie: ^1.7.1
  youtube_player_flutter: ^8.1.2
  
  # PDF & Documents
  pdf: ^3.10.6
  printing: ^5.11.1
  
  # Utilities
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.1
  
  # Firebase (Analytics, Crashlytics)
  firebase_core: ^2.24.0
  firebase_analytics: ^10.7.0
  firebase_crashlytics: ^3.4.0
  
  # AI & Speech
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.3
  
  # Charts & Gamification
  fl_chart: ^0.65.0
  
  # Hijri Calendar
  hijri: ^3.0.0
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
    - assets/fonts/
    - assets/templates/
    - assets/data/quran/
    - assets/data/translations/
  
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: ScheherazadeNew
      fonts:
        - asset: assets/fonts/ScheherazadeNew-Regular.ttf
        - asset: assets/fonts/ScheherazadeNew-Bold.ttf
          weight: 700
